### PR TITLE
Added rel attribute configuration

### PR DESCRIPTION
**Pull request by mvanduijker**
So we can do tricks like https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/ when using target _blank.

### CODE REVIEW

**Comment by mvanduijker** [comment]
ping

**Comment by xi** [comment]
This would also fix #4.

**Comment by kruncher** [comment]
Thank you for your contribution; this looks good to me 👍

**Comment by kruncher** [comment]
I have just pushed this to npm.

**Pull request merged**
